name: CI

on: [pull_request, push]

permissions: {}

jobs:
  build_test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: 24
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: npm test
      - name: Report Compressed Size
        uses: ./
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          pattern: index.js