name: CI

on: [pull_request, push]

permissions:
  contents: read

jobs:
  build_test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      - run: npm ci
      - run: npm run build
      - run: npm test
      - name: Report Compressed Size
        uses: ./
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          pattern: index.js
